version: '3.3'

services:
  nuxt:
    build: .
    image: nuxt_ui_dev
    container_name: nuxt_prjct_ui
    command: sleep infinity
    volumes:
    - .:/app
    # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
    - /app/node_modules
    ports:
      - "3000:3000"
